In [1]:
a = 10

In [2]:
a

10

In [3]:
import pandas as pd

data = pd.read_csv('C:\\Users\\Van Phu Hoa\\PycharmProjects\\income_outcome\\{}\\{}_{}.csv'.format('outcome','Jan', 'outcome'))

In [4]:
data

          Date                          List               Type   Amount
0     8/1/2021                  Pho Nam Dinh          necessity    30000
1    11/1/2021                  Pho Nam Dinh          necessity    30000
2    10/1/2021                      ministop          necessity    61000
3   14/01/2021                Hu tieu bo kho          necessity    30000
4   14/01/2021                        Xoi ga          necessity    15000
5   14/01/2021                  Chicken rice          necessity    25000
6   16/01/2021             Gako Chicken Rice          necessity    70000
7   16/01/2021           Traditional Milktea          necessity    19000
8   19/01/2021                        Xoi ga          necessity    15000
9   19/01/2021             Rice rolls + cake          necessity    29000
10  21/01/2021                    3 banh gio          necessity    40000
11  26/01/2021                      banh gio          necessity    13000
12  26/01/2021                   banh mi que          necessity    13000
13  26/01/2021            com cuon + com nam          necessity    31000
14  30/01/2021                           BBQ          necessity   129000
15    6/1/2021                           BHX          necessity   148000
16  19/01/2021                           BHX          necessity   105000
17    4/1/2021             Fcode Train C fee          education   100000
18  20/01/2021  Buy red t-shirt at Bay store               play   395000
19  22/01/2021                     something               play   500000
20  28/01/2021              sinh to bo + bhx               play    84000
21    8/1/2021              parking 1st week          necessity    18000
22    5/1/2021                   fulfill gas          necessity    50000
23   10/1/2021                parking Hoa L?          necessity    10000
24  16/01/2021              parking 2nd week          necessity    17000
25  16/01/2021              parking Coopmart          necessity     3000
26  16/01/2021          parking Vincom plaza          necessity     6000
27  16/01/2021                   fulfill gas          necessity    50000
28  22/01/2021              parking 3rd week          necessity    21000
29  19/01/2021                   fulfill gas          necessity    50000
30  25/01/2021                   fulfill gas          necessity    40000
31  30/01/2021              parking 4th week          necessity    22000
32  28/01/2021                   fulfill gas          necessity    55000
33  29/01/2021                          grab          necessity    82000
34  18/01/2021                    invest HUT  financial freedom   500000
35  20/01/2021           Fcode monthly cost           necessity    30000
36    3/1/2021                          BigO          necessity   100000
37    1/1/2021                         aaaaa          education  1000000
38    1/1/2011                         asdsd            savings     1000

In [5]:
data.loc[0]

Date          8/1/2021
List      Pho Nam Dinh
Type         necessity
Amount           30000
Name: 0, dtype: object